### ISSUE TITLE
correct grammar

### ISSUE THREAD

**Issue by plazotronik** [netology-code/dj-homeworks#33]
https://github.com/netology-code/dj-homeworks/blob/0420d5da818fb2c5eaa288ba7e0dae0cb8b3ec10/request-handling/file_server/README.md#L26

строка вынесена в подпункт, зачем то...

https://github.com/netology-code/dj-homeworks/blob/0420d5da818fb2c5eaa288ba7e0dae0cb8b3ec10/request-handling/file_server/README.md#L28

вероятнее всего должно быть "одноименный"

https://github.com/netology-code/dj-homeworks/blob/0420d5da818fb2c5eaa288ba7e0dae0cb8b3ec10/request-handling/file_server/app/templates/index.html#L29

слитно

**Comment by prokaktus** [comment]
Done!
